// <auto-generated />
using System;
using Inviter.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inviter.Server.Migrations
{
    [DbContext(typeof(InviterContext))]
    [Migration("20220329193914_Invites")]
    partial class Invites
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inviter.Server.Models.Invite", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<decimal>("FromID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("from_id");

                    b.Property<decimal[]>("Lobby")
                        .IsRequired()
                        .HasColumnType("numeric(20,0)[]")
                        .HasColumnName("lobby");

                    b.Property<Instant>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("ToID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("to_id");

                    b.HasKey("ID")
                        .HasName("pk_invites");

                    b.HasIndex("FromID")
                        .HasDatabaseName("ix_invites_from_id");

                    b.HasIndex("ToID")
                        .HasDatabaseName("ix_invites_to_id");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Inviter.Server.Models.User", b =>
                {
                    b.Property<decimal>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<bool>("AllowInvitesFromEveryone")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_invites_from_everyone");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<Instant>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<decimal?>("UserID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("ID")
                        .HasName("pk_users");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_users_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Inviter.Server.Models.Invite", b =>
                {
                    b.HasOne("Inviter.Server.Models.User", "From")
                        .WithMany()
                        .HasForeignKey("FromID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_from_id");

                    b.HasOne("Inviter.Server.Models.User", "To")
                        .WithMany()
                        .HasForeignKey("ToID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_to_id");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Inviter.Server.Models.User", b =>
                {
                    b.HasOne("Inviter.Server.Models.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserID")
                        .HasConstraintName("fk_users_users_user_id");
                });

            modelBuilder.Entity("Inviter.Server.Models.User", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
